[package]
name = "sleeper"
version = "0.1.0"
authors = ["Paul Houghton <paulirotta@gmail.com>"]
edition = "2018"

[features]
default = []

[dependencies.gpio]
rppal = "0.9"
default-features = false
optional = true
